{% set name = "pyUSID" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4d77141a9407f67568c8ccb17750e0da72b1b44ab9d79fb86475c885cc8e2d58

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
  run:
    - python >={{ python_min }}
    - numpy >=1.10
    - dask-core >=0.10
    - h5py >=2.6.0
    - matplotlib-base >=2.0.0
    - psutil
    - six
    - joblib >=0.11.0
    - ipywidgets >=5.2.2
    - ipython
    - pillow
    - sidpy >=0.0.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyUSID

about:
  home: https://github.com/pycroscopy/pyUSID
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Framework for storing, visualizing, and processing Universal Spectroscopic and Imaging Data (USID)
  doc_url: https://pycroscopy.github.io/pyUSID/
  dev_url: https://github.com/pycroscopy/pyUSID

extra:
  recipe-maintainers:
    - ssomnath
    - compphyschris
    - carlodri
