{% set name = "pyUSID" %}
{% set version = "0.0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 27dde32d3ce7c93daf062c9e796ed2cbbf76dc043f373c52e1b5810c5279839b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - numpy >=1.10
    - dask >=0.10
    - h5py >=2.6.0
    - matplotlib >=2.0.0
    - psutil
    - six
    - joblib >=0.11.0
    - ipywidgets >=5.2.2
    - ipython >=5.1.0,<6  # [py2k]  # IPython 6.0+ does not support Python 2.6, 2.7, 3.0, 3.1, or 3.2
    - ipython >=6.0  # [py3k]  # Beginning with IPython 6.0, Python 3.3 and above is required.
    - pyqt >=5  # [py3k]
    - unittest2  # [py2k]
    - pillow

test:
  imports:
    - pyUSID

about:
  home: https://github.com/pycroscopy/pyUSID
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Framework for storing, visualizing, and processing Universal
    Spectroscopic and Imaging Data (USID)'
  doc_url: https://pycroscopy.github.io/pyUSID/
  dev_url: https://github.com/pycroscopy/pyUSID

extra:
  recipe-maintainers:
    - ssomnath
    - compphyschris
    - carlodri
